title: ADA526 Applied Robot Prototyping
description: Course material and documentation for ADA526 Applied Robot Prototyping.
theme: just-the-docs

url: https://frdedynamics.github.io/ADA526

aux_links:
  Page Repository: https://github.com/frdedynamics/ADA526
  
logo: "/assets/images/hvlRobotics_v_medium_white.png"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
